POST http://localhost:3000/items

Content-Type: application/json

{
    "image": "Publicar250000000012008_A.JPG",
    "title": "MOUSE GENIUS DX-110 USB",
    "precio": 230.0
}

###

GET https://localhost/

###

GET https://localhost/items

###

GET https://localhost/img/Publicar250000000012008_A.JPG

###

POST  https://localhost/register
Content-Type: application/json

{
"email": "raul.lujan@gmail.com",
"password": "123456"
}

  ###